// Code generated by scripts/runtime_matrix.py; DO NOT EDIT.
// Production exact-cell admission/scheduling/receipt authority; physical proof remains open.

package main

const generatedRuntimeMatrixVersion = "2026-07-13.1"
const generatedRuntimeMatrixSHA256 = "a0416a5205ae32bdd5d9c40860f004af913e9a3aa0287b49768f098b5d7f69b0"
const generatedRuntimeMatrixGateProven = false

type generatedRuntimeCapability struct {
	ID              string
	Runtime         string
	Engine          string
	Device          string
	HardwareClasses []string
	Job             string
	Model           string
	ModelKind       string
	Runner          string
	MinMemoryGB     float64
	Verification    string
}

var generatedAdvertisedRuntimeCapabilities = []generatedRuntimeCapability{
	{
		ID:              "candle-metal-llama1-classify",
		Runtime:         "candle_metal",
		Engine:          "candle",
		Device:          "metal",
		HardwareClasses: []string{"apple_silicon_base", "apple_silicon_max", "apple_silicon_pro", "apple_silicon_ultra"},
		Job:             "batch_classification",
		Model:           "llama-3.2-1b-instruct-q4",
		ModelKind:       "gguf",
		Runner:          "batch_classification",
		MinMemoryGB:     4,
		Verification:    "label",
	},
	{
		ID:              "candle-metal-llama1-extract",
		Runtime:         "candle_metal",
		Engine:          "candle",
		Device:          "metal",
		HardwareClasses: []string{"apple_silicon_base", "apple_silicon_max", "apple_silicon_pro", "apple_silicon_ultra"},
		Job:             "json_extraction",
		Model:           "llama-3.2-1b-instruct-q4",
		ModelKind:       "gguf",
		Runner:          "json_extraction",
		MinMemoryGB:     4,
		Verification:    "canonical_json",
	},
	{
		ID:              "candle-metal-llama1-infer",
		Runtime:         "candle_metal",
		Engine:          "candle",
		Device:          "metal",
		HardwareClasses: []string{"apple_silicon_base", "apple_silicon_max", "apple_silicon_pro", "apple_silicon_ultra"},
		Job:             "batch_infer",
		Model:           "llama-3.2-1b-instruct-q4",
		ModelKind:       "gguf",
		Runner:          "batch_infer",
		MinMemoryGB:     4,
		Verification:    "byte_exact",
	},
	{
		ID:              "candle-metal-minilm-embed",
		Runtime:         "candle_metal",
		Engine:          "candle",
		Device:          "metal",
		HardwareClasses: []string{"apple_silicon_base", "apple_silicon_max", "apple_silicon_pro", "apple_silicon_ultra"},
		Job:             "embed",
		Model:           "all-minilm-l6-v2",
		ModelKind:       "hf",
		Runner:          "embed",
		MinMemoryGB:     2,
		Verification:    "cosine",
	},
	{
		ID:              "candle-metal-minilm-rerank",
		Runtime:         "candle_metal",
		Engine:          "candle",
		Device:          "metal",
		HardwareClasses: []string{"apple_silicon_base", "apple_silicon_max", "apple_silicon_pro", "apple_silicon_ultra"},
		Job:             "rerank",
		Model:           "all-minilm-l6-v2",
		ModelKind:       "hf",
		Runner:          "rerank",
		MinMemoryGB:     2,
		Verification:    "order",
	},
	{
		ID:              "candle-metal-whisper-base",
		Runtime:         "candle_metal",
		Engine:          "candle",
		Device:          "metal",
		HardwareClasses: []string{"apple_silicon_base", "apple_silicon_max", "apple_silicon_pro", "apple_silicon_ultra"},
		Job:             "audio_transcribe",
		Model:           "whisper-base",
		ModelKind:       "hf",
		Runner:          "whisper",
		MinMemoryGB:     2,
		Verification:    "byte_exact",
	},
	{
		ID:              "candle-metal-whisper-tiny",
		Runtime:         "candle_metal",
		Engine:          "candle",
		Device:          "metal",
		HardwareClasses: []string{"apple_silicon_base", "apple_silicon_max", "apple_silicon_pro", "apple_silicon_ultra"},
		Job:             "audio_transcribe",
		Model:           "whisper-tiny",
		ModelKind:       "hf",
		Runner:          "whisper",
		MinMemoryGB:     1,
		Verification:    "byte_exact",
	},
}

type generatedRuntimeCellTruth struct {
	ID         string
	Runtime    string
	Job        string
	Model      string
	ModelKind  string
	Lifecycle  string
	Advertised bool
}

var generatedRuntimeCellTruths = []generatedRuntimeCellTruth{
	{ID: "apple-cluster-405b-infer", Runtime: "apple_cluster", Job: "batch_infer", Model: "llama-3.1-405b-instruct-q4", ModelKind: "mlx", Lifecycle: "stub", Advertised: false},
	{ID: "candle-cpu-llama1-infer", Runtime: "candle_cpu", Job: "batch_infer", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "wire_only", Advertised: false},
	{ID: "candle-cpu-minilm-embed", Runtime: "candle_cpu", Job: "embed", Model: "all-minilm-l6-v2", ModelKind: "hf", Lifecycle: "wire_only", Advertised: false},
	{ID: "candle-cpu-whisper-tiny", Runtime: "candle_cpu", Job: "audio_transcribe", Model: "whisper-tiny", ModelKind: "hf", Lifecycle: "wire_only", Advertised: false},
	{ID: "candle-cuda-llama1-classify", Runtime: "candle_cuda", Job: "batch_classification", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-cuda-llama1-extract", Runtime: "candle_cuda", Job: "json_extraction", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-cuda-llama1-infer", Runtime: "candle_cuda", Job: "batch_infer", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-cuda-minilm-embed", Runtime: "candle_cuda", Job: "embed", Model: "all-minilm-l6-v2", ModelKind: "hf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-cuda-minilm-rerank", Runtime: "candle_cuda", Job: "rerank", Model: "all-minilm-l6-v2", ModelKind: "hf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-cuda-whisper-base", Runtime: "candle_cuda", Job: "audio_transcribe", Model: "whisper-base", ModelKind: "hf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-cuda-whisper-tiny", Runtime: "candle_cuda", Job: "audio_transcribe", Model: "whisper-tiny", ModelKind: "hf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-metal-bge-embed", Runtime: "candle_metal", Job: "embed", Model: "bge-small-en-v1.5", ModelKind: "hf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-metal-llama1-classify", Runtime: "candle_metal", Job: "batch_classification", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "production", Advertised: true},
	{ID: "candle-metal-llama1-extract", Runtime: "candle_metal", Job: "json_extraction", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "production", Advertised: true},
	{ID: "candle-metal-llama1-infer", Runtime: "candle_metal", Job: "batch_infer", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "production", Advertised: true},
	{ID: "candle-metal-minilm-embed", Runtime: "candle_metal", Job: "embed", Model: "all-minilm-l6-v2", ModelKind: "hf", Lifecycle: "production", Advertised: true},
	{ID: "candle-metal-minilm-rerank", Runtime: "candle_metal", Job: "rerank", Model: "all-minilm-l6-v2", ModelKind: "hf", Lifecycle: "production", Advertised: true},
	{ID: "candle-metal-msmarco-rerank", Runtime: "candle_metal", Job: "rerank", Model: "ms-marco-minilm-l6-v2", ModelKind: "hf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-metal-qwen05-infer", Runtime: "candle_metal", Job: "batch_infer", Model: "qwen2.5-0.5b-instruct-q4", ModelKind: "gguf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-metal-qwen7-classify", Runtime: "candle_metal", Job: "batch_classification", Model: "qwen2.5-7b-instruct-q4", ModelKind: "gguf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-metal-qwen7-extract", Runtime: "candle_metal", Job: "json_extraction", Model: "qwen2.5-7b-instruct-q4", ModelKind: "gguf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-metal-qwen7-infer", Runtime: "candle_metal", Job: "batch_infer", Model: "qwen2.5-7b-instruct-q4", ModelKind: "gguf", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "candle-metal-whisper-base", Runtime: "candle_metal", Job: "audio_transcribe", Model: "whisper-base", ModelKind: "hf", Lifecycle: "production", Advertised: true},
	{ID: "candle-metal-whisper-tiny", Runtime: "candle_metal", Job: "audio_transcribe", Model: "whisper-tiny", ModelKind: "hf", Lifecycle: "production", Advertised: true},
	{ID: "container-cuda-custom", Runtime: "container_cuda", Job: "custom", Model: "", ModelKind: "", Lifecycle: "hardware_pending", Advertised: false},
	{ID: "hawking-metal-llama1-infer", Runtime: "hawking_metal", Job: "batch_infer", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "soak_only", Advertised: false},
	{ID: "mlx-metal-llama1-classify", Runtime: "mlx_metal", Job: "batch_classification", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "stub", Advertised: false},
	{ID: "mlx-metal-llama1-extract", Runtime: "mlx_metal", Job: "json_extraction", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "stub", Advertised: false},
	{ID: "mlx-metal-llama1-infer", Runtime: "mlx_metal", Job: "batch_infer", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "stub", Advertised: false},
	{ID: "vllm-cuda-llama1-classify", Runtime: "vllm_cuda", Job: "batch_classification", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "soak_only", Advertised: false},
	{ID: "vllm-cuda-llama1-extract", Runtime: "vllm_cuda", Job: "json_extraction", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "soak_only", Advertised: false},
	{ID: "vllm-cuda-llama1-infer", Runtime: "vllm_cuda", Job: "batch_infer", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "soak_only", Advertised: false},
	{ID: "vllm-cuda-llama1-rerank", Runtime: "vllm_cuda", Job: "rerank", Model: "llama-3.2-1b-instruct-q4", ModelKind: "gguf", Lifecycle: "soak_only", Advertised: false},
	{ID: "wire-eval", Runtime: "contract_only", Job: "eval", Model: "", ModelKind: "", Lifecycle: "wire_only", Advertised: false},
	{ID: "wire-image-gen", Runtime: "contract_only", Job: "image_gen", Model: "", ModelKind: "", Lifecycle: "wire_only", Advertised: false},
	{ID: "wire-lora", Runtime: "contract_only", Job: "lora_finetune", Model: "", ModelKind: "", Lifecycle: "wire_only", Advertised: false},
}

var generatedRuntimePhase2Blockers = []string{
	"Hardware-pending and soak-only cells still require release packaging, physical receipts, promotion policy, and sustained multi-machine evidence.",
	"The DB model catalog and control seed remain duplicated and lack lifecycle/availability fields; startup validation now catches missing or unsafe advertised rows.",
	"Worker engine, hardware class, and device identity remain self-declared rather than remotely attested.",
}
